application: modo-patrone-ws
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /(.*\.html)
  static_files: static/\1
  upload: static/(.*\.html)

- url: /js/(.*\.js)
  static_files: static/js/\1
  upload: static/js/(.*\.js)

- url: /css/(.*\.(css|eot|svg|ttf|woff))
  static_files: static/css/\1
  upload: static/css/(.*\.(css|eot|svg|ttf|woff))

- url: /img/(.*\.(gif|png|jpg))
  static_files: static/img/\1
  upload: static/img/(.*\.(gif|png|jpg))

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /admin.*
  script: admin.app
  login: admin

- url: /.*
  script: main.app
